version: "3.8"

services:
  fsb:
      build: .
      restart: unless-stopped
      container_name: fsb
      environment:
      # required
       - API_ID=29684228 # change this to your ID
       - API_HASH=9c201a654e8fc97576ce5c077cf529d2 # change this to your HASH
       - BOT_TOKEN=5921593659:AAFn_vDTiDebW26onCbfZkbPw1fE-HnrpAQ #TGFileDownloadBot
       - BIN_CHANNEL=-1001872367843 # paste channel ID
      ports:
       - 127.0.0.1:8000:80
      volumes:
       - $HOME/TG-FileStreamBot:/app/.env
